language: node_js

cache:
  directories:
    - ~/.npm
    
node_js:
  - '8'
  - '10'
  - '12'

git:
  depth: 3

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

env:
  global:
    - NODE_ENV=test
    - PORT=3000
    - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
    - JWT_EXPIRATION_MINUTES=15

script:
  - yarn validate

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn coverage
